---
- hosts: all
  remote_user: vincent
  become: true

  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your GitHub user name"
      private: false
    - name: "githubpassword"
      prompt: "Enter your GitHub password"
      private: true

  tasks:
    - name: update package repository
      become: true
      apt:
        name: mosh
        update-cache: true

    - name: install basic packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - 'mosh'
        - 'python'
        - 'python3'
        - 'htop'
        - 'git'
        - 'ruby-full'

    - include: tasks/installVim.yml
    - include: tasks/installTmux.yml
    - include: tasks/installZsh.yml
    - include: tasks/installBash.yml

    - name: cloning dotfiles
      become: false
      git:
        repo: https://{{ githubuser }}:{{ githubpassword }}@github.com/vdenoise/dotfiles.git
        dest: /home/vincent/dotfiles
        force: true

    - name: symlink files
      become: false
      file:
        src: '/home/vincent/dotfiles/{{item.src}}'
        dest: '/home/vincent/{{item.dest}}'
        state: link
        force: true
      with_items:
        - {src: 'vimrc', dest: '.vimrc'}
        - {src: 'tmuxconf', dest: '.tmux.conf'}
        - {src: 'tmuxconflocal', dest: '.tmux.conf.local'}
        - {src: 'bashrc', dest: '.bashrc'}
        - {src: 'zshrc', dest: '.zshrc'}

- hosts: dev
  remote_user: vincent
  become: true
  tasks:
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present
    - include: tasks/installDevPack.yml
    - include: tasks/installPythonPack.yml
    - include: tasks/installLatex.yml
    - include: tasks/installDevOps.yml

- hosts: webserver
  remote_user: vincent
  become: true
  tasks:
    - include: tasks/installDevOps.yml
