---
- name: Install Various DevOps package
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - snapd

- name: Install terraform with snap
  become: true
  command: snap install terraform

- name: install docker with snap
  become: true
  command: snap install docker

- name: launch docker
  become: true
  systemd:
    name: docker
    state: started
...
