---
- name: install zsh
  become: true
  apt:
    name: "{{ item }}"
    state: present
  vars:
    item: zsh

- name: Installing Zsh and git
  become: true
  apt: pkg=zsh,git state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
  when: installation is success

- name: Cloning  oh-my-zsh
  become: false
  git:
    repo: https://{{ githubuser }}:{{ githubpassword }}@github.com//robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    force: true
  when: installation is success
  register: cloning

- name: Cloning  oh-my-zsh / autosuggest
  become: false
  git:
    repo: https://{{ githubuser }}:{{ githubpassword }}@github.com//zsh-users/zsh-autosuggestions 
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
    force: true
  when: installation is success

- name: Cloning  oh-my-zsh / syntax highlighting
  become: false
  git:
    repo: https://{{ githubuser }}:{{ githubpassword }}@github.com//zsh-users/zsh-syntax-highlighting 
    dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
    force: true
  when: installation is success

- name: Cloning  oh-my-zsh / Powerline 9K
  become: false
  git:
    repo: https://{{ githubuser }}:{{ githubpassword }}@github.com//bhilburn/powerlevel9k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    force: true
  when: installation is success
...
