---
- name: install aptitude for upgrade
  become: true
  apt:
    name: aptitude
    state: present

- name: install dev packages
  become: true
  tags: dev
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - gcc
    - g++
    - gfortran
    - libcurl-dev
    - libssl-dev
    - libblas-dev
    - liblapack-dev
    - sysstat
    - htop
    - git
    - subversion
    - mercurial
    - python-samba
    - vim
    - neovim
    - vagrant
    - rdesktop
    - openvpn
    - python-dev
    - r-base
    - r-recommended
    - inkscape
    - ruby-dev
    - sqlite
    - pgadmin3
    - postgresql
    - libpq-dev
    - python-psycopg2
    - imagemagick
    - marble
    - mapserver-bin
    - python-mapscript
    - python-matplotlib
    - liblas-bin
    - gdal-bin
    - python-gdal
    - grass
    - libspatialite-dev
    - spatialite-gui
    - spatialite-bin
    - qgis
    - pandoc
    - xclip
    - filezilla
    - gummi
    - texmaker
    - keepassx
    - wireshark
    - cifs-utils
..f
