---
- name: Install Various DevOps package
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - snapd

- name: Install terraform with snap
  become: true
  command: sudo snap install terraform && sudo snap install docker
...
