---
- name: make sure pip is installed
  become: true
  apt:
    name: "{{ item}}"
    state: present
  with_items:
    - python-pip
    - python3-pip

- name: Install global python requirementsi
  become: false
  pip: name={{item}} state=present
  with_items:
    - pandas
    - scipy
    - shapely
    - django
    - pyshp
    - geopy
    - pyproj
    - ipython
    - ipdb
    - scikit-learn
    - pyzmq
    - tornado
    - pygments
    - sphinx
    - patsy
    - statsmodels
    - ggplot
    - rpy2
    - fabric
...
