---
- name: Install Various DevOps package
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - docker
    - snapd

- name: Install terraform with snap
  become: true
  snap:
    name: terraform
    state: latest
...
